// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace MasterSite.Core.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WHATEVER : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WHATEVER));
        
        string IMigrationMetadata.Id
        {
            get { return "201508290230152_WHATEVER"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
